module.exports = [
  {
    id: 0,
    title: `서울 강남구 축구하실 분 구합니다 `,
    city: 0,
    sportsTypes: [5],
    content:
      '강남역 근처 풋살장에서 축구하실 분 구합니다. 연령 상관 없습니다. 편하게 댓글 남겨 주세요',
    date: '2021-12-13',
    recruit: true,
    likeCount: 10,
    owner: { id: 'test2', nickname: '강남구원펀치' },
    comments: [
      {
        id: 1,
        content: 'ㅋㅋㅋ 닉네임 웃기네요',
        date: '2021-12-13',
        owner: { id: 1, nickname: '도봉구왕주먹' },
      },
      {
        id: 2,
        content: '강남역 근처에 풋살장도 있었나',
        date: '2021-12-14',
        owner: { id: 2, nickname: '한강러닝머신건' },
      },
    ],
  },
  {
    id: 1,
    title: `노원구 농구하실 3명 구합니다.`,
    city: 0,
    sportsTypes: [2, 5],
    content: '이번 주 주말에 노원구 농구하실 3명 구합니다.',
    date: '2021-12-13',
    recruit: true,
    likeCount: 3,
    owner: { id: 3, nickname: '토끼' },
    comments: [
      {
        id: 1,
        content: '농구장 위치는 어디인가요?',
        date: '2021-12-13',
        owner: { id: 0, nickname: '슬램덩크팬' },
      },
      {
        id: 2,
        content: '중랑천 쪽에 농구장 있는데',
        date: '2021-12-14',
        owner: { id: 1, nickname: '호랑이' },
      },
      {
        id: 3,
        content: '저희 4명인데 괜찮을까요?',
        date: '2021-12-14',
        owner: { id: 2, nickname: '원숭이' },
      },
    ],
  },
  {
    id: 2,
    title: `Hi, we are global football team.`,
    city: 2,
    sportsTypes: [4],
    content:
      'hello, we are No.1 Team of EPL. we want to play football with koeans',
    date: '2021-12-14',
    recruit: true,
    likeCount: 1,
    owner: { id: 2, nickname: '원숭이' },
    comments: [
      {
        id: 1,
        content: "sorry I can't speak english.",
        date: '2021-12-14',
        owner: { id: 2, nickname: 'korean' },
      },
    ],
  },
  {
    id: 3,
    title: `당구 치실 40대 남성분?`,
    city: 3,
    sportsTypes: [3],
    content: '광주입니다. 당구 4구 200 이상 치시는 분',
    date: '2021-12-14',
    recruit: false,
    likeCount: 0,
    owner: { id: 0, nickname: '으르렁' }, // user id
    comments: [],
  },
  {
    id: 4,
    title: `야구팀 모집합니다.`,
    city: 1,
    sportsTypes: [1],
    content: '부산 취미로 야구하실 분',
    date: '2021-12-14',
    recruit: true,
    likeCount: 1,
    owner: { id: 0, nickname: '으르렁' }, // user id
    comments: [],
  },
  {
    id: 5,
    title: `볼링 치실 분? 볼링 치실 분? 볼링 치실 분 볼링 치실 분 볼링 치실 분`,
    city: 4,
    sportsTypes: [0],
    content: '강릉인데, 볼링 치실 분?ㅋㅋㅋㅋ',
    date: '2021-12-16',
    recruit: true,
    likeCount: 2,
    owner: { id: 1, nickname: '으르렁' }, // user id
    comments: [],
  },
  {
    id: 6,
    title: `제주도에서 운동하실 분`,
    city: 14,
    sportsTypes: [0, 1, 2, 3, 4, 5, 6],
    content: '제주도 운동하실 분?',
    date: '2021-12-15',
    recruit: true,
    likeCount: 102,
    owner: { id: 0, nickname: '으르렁' }, // user id
    comments: [],
  },
  {
    id: 7,
    title: `서울에서 운동하실 분`,
    city: 0,
    sportsTypes: [5],
    content: '울산 북구입니다. 배드민턴 취미로 하시는 분?',
    date: '2021-12-15',
    recruit: false,
    likeCount: 0,
    owner: { id: 0, nickname: '으르렁' }, // user id
    comments: [],
  },
  {
    id: 8,
    title: `경기도에서 운동하실 분`,
    city: 6,
    sportsTypes: [2],
    content: '울산 북구입니다. 배드민턴 취미로 하시는 분?',
    date: '2021-12-15',
    recruit: true,
    likeCount: 0,
    owner: { id: 0, nickname: '으르렁' }, // user id
    comments: [],
  },
  {
    id: 9,
    title: `부산에서 운동하실 분`,
    city: 1,
    sportsTypes: [0],
    content: '울산 북구입니다. 배드민턴 취미로 하시는 분?',
    date: '2021-12-15',
    recruit: true,
    likeCount: 0,
    owner: { id: 0, nickname: '으르렁' }, // user id
    comments: [],
  },
  {
    id: 10,
    title: `강원도에서 운동하실 분`,
    city: 7,
    sportsTypes: [0],
    content: '울산 북구입니다. 배드민턴 취미로 하시는 분?',
    date: '2021-12-15',
    recruit: true,
    likeCount: 0,
    owner: { id: 0, nickname: '으르렁' }, // user id
    comments: [],
  },
];
